### ISSUE TITLE
Canvas editor

### ISSUE THREAD

**Issue by sammeltassen** [digirati-co-uk/iiif-manifest-editor#17]
Current manifest editor creates (arbitrary?) canvasses of 1000x1000px. Aspect ratio can only be adapted by fitting canvas to image.

For composing canvasses consisting of multiple image annotations, both the size and the proportion of the canvas should be adaptable.

Size is a tricky thing when one starts scaling annotations on the canvas.

See for example the canvasses with multiple objects here: https://heritage.tudelft.nl/en/exhibitions/novieten. The aspect ratio of the canvas determines the way the objects appear on the exhibition page.

**Comment by sammeltassen** [comment]
Currently, canvas size is also related to zoom controls. So If I create a new canvas, add an image to it, I cannot zoom it because the canvas is 1000px (while the image is much larger of course).

**Comment by sammeltassen** [comment]
Cropping images in current tool resets their size so that the resulting crop needs to be scaled back on the canvas. As there's nothing outside of the canvas, this is often impossible.

How to conceptualise the canvas and its surroundings in the editor? Maybe it's an endless drawing board on which the canvas itself is presented as a (kind of) annotation. I'm thinking of the artboards as used in Illustrator. Isn't it theoretically possible to put annotations halfway on the canvas? Can they have negative coordinates? Creatively, these kind of options are inspiring, but they require a more flexible approach to what a canvas is, separate from the annotations.

**Comment by sammeltassen** [comment]
To further the Illustrator analogy: for composition, it's beneficial to have the equivalent of smart guides or a grid to snap to (also when scaling annotations).

For anyone wondering what all this might be good for: think of [Aby Warburg's Mnemosyne Atlas](https://warburg.library.cornell.edu/panel/b) or the work of [Batia Suter](http://www.batiasuter.org). Or a (non-IIIF) project like this allowing visitors to create their own custom display of archeological objects: https://belowthesurface.amsterdam/en/vitrines.

While Mirador offers a (non-IIIF) way to juxtapose different manifests next to each other, the manifest editor allows editors to actually compose canvasses of multiple IIIF-images from different sources, while being able to crop/rotate/scale each of them. Especially the modifications show the curator's hand, which is often not tangible in digital presentations. For me, this is one of the most exciting aspects of the editor.

**Comment by sammeltassen** [comment]
For negative xy, not clear if this is possible or allowed, but wh could be larger than canvas size: https://www.w3.org/TR/media-frags/#naming-space

**Comment by stephenwf** [comment]
Some similar work here:
https://github.com/atlas-viewer/atlas/blob/master/src/world.ts#L317-L343

What this model lets you do is create a world with a varying size, and then place images at fixed size in it. So you could, for example, have 4 1000x1000 images tiled in a 2x2. However you're not limited to painting the images at the size they are. Instead you could paint them all at 500x500 and still have a world that is 1000x1000.

The choice of how "big" the canvas ends up being could be done automatically from maybe the largest asset, or could be an editorial choice. If you image having a composition that looks like this:

```
 [ 250 x 250 ]   [ 1500 x 1500 ]
 [ 500 x 500]    [ 500 x 500 ]
```
(all squares displayed at the same size)

Because the 250x250 is not very high resolution, you may make an editorial decision to make the canvas width in this case 750x750. So a balance between the max (3000x3000) and the minimum (500x500) for the given image sizes.

**Comment by sammeltassen** [comment]
To be clear: I don't think there's much of a use case for manually setting canvas dimensions (contrary to aspect ratio, where I do see a use case), so it makes sense to do this automatically on the basis of the largest, or perhaps rather the smallest annotation on the canvas (to avoid scaling beyond original size). I hope the calculations are manageable with a large number of annotations on a single canvas...

**Comment by tomcrane** [comment]
If you think of a tool like Lucidchart, you never really need to think about the "paper" size. Although it still operates in units of A4 (or whatever you have chosen) you always end up just cropping to content.

It's a special case to say that you really want "paper" size of something other than the best fit.

Speaking of Lucidchart, I wonder how much like the editing / layout experience of this tool the manifest editor is _per canvas_? A layout surface...

**Comment by tomcrane** [comment]
We have to remember that unlike Lucidchart, most users of the manifest editor will only be putting one object (image) on each page (canvas), and won't be thinking about the fact that the canvas dimensions and extent could be different from their image. Whatever we do it shouldn't complicate this base use case but be a natural extension of it when someone is making a canvas with complex composition. By _complex_, I mean anything other than one image filling the entire canvas.

**Comment by tomcrane** [comment]
Common scenario: I have 100 book page images and I need to arrange them in sequence, make a table of contents, add some metadata.
In the user's model the canvas doesn't really exist, it's just a sequence of images.

Less common scenario - I want to make this:

![image](https://user-images.githubusercontent.com/1443575/140778950-4f49cdec-9e0c-469d-85f4-ba168ffbff1b.png)

...so I need to be able to arrange and stack things, and think about the shape of the page/canvas distinct from its content.

The challenge is to make both of these feel natural. They aren't special modes or different UIs.

**Comment by stephenwf** [comment]
@tomcrane in that example above, if you had just created that - as a user how would you like the options for the size of the overall canvas to be presented? We could take into account the largest possible, and largest without losing detail (i.e. based on the smallest image).

**Comment by tomcrane** [comment]
The Mona Lisa example? The difficulty here is that there is only one piece of content. In normal operation, that would dictate the dimensions of the canvas and I'd end up with just the full Mona Lisa.

To get the effect I want, I'd need to separately make the shape of the canvas, and then move the Mona Lisa partially of off it. 

If you mean the immediate multi-image above example - I don't see a problem with just defaulting to the largest possible. They are just integers, not pixels, so we have plenty of room. This illustrates a problem with the previous editor, when you drag an image in that is much "bigger" than the canvas... that "bigger" doesn't make any sense, because there is no required relationship between the canvas coordinates and the pixel dimensions of the image resources; we just set them the same for single-image canvases for convenience.

Say I have a 2000 x 1000 w,h canvas and I drag a 10,000 x 10,000 _pixel_ image onto it... the editor has no information at all to determine how much of the canvas that image takes up, so it definitely shouldn't appear huge, much bigger than the canvas. There should in fact be some default behaviour that just makes the introduced image a comfortable size in the viewport. The editor has no idea what you'll be doing with that image and shouldn't make assumptions based on its pixel dimensions.

**Comment by tomcrane** [comment]
Almost all the time it will be fine for the manifest editor app to just make that decision for the user - to expand the canvas integer dimensions to accommodate the numeric pixel values.

The canvas could be deliberately "locked" by the editor in two special cases:

1. the user has modified the canvas boundaries (e.g., by dragging, or entering numbers manually) to be different from the outer bounding rectangle of the resource(s) and then saved the manifest. This adds a `dimensions-locked` behaviour to the canvas automatically - user is up to something so don't interfere. E.g., in https://github.com/digirati-co-uk/iiif-manifest-editor/issues/17#issuecomment-963323034 the user saved the canvas with borders beyond the bounding rectangle of the content, so just leave it and lock it. It would be very rare that the w,h the canvas ends up with was unsatisfactory from a "resolution" point of view - but even then (even more edge) you could still modify w,h later.
2. the user explicitly checks a box in the UI that does the same thing - they want to keep the current coordinate system even if they later add a detail image that is a "higher resolution" - this is so edge-case that we shouldn't design the UI around it. 

[x] lock canvas dimensions

 - Most users, all of the time do not need to think about Canvas dimensions at all.
 - Some users, some of the time will need to modify canvas dimensions or have multiple resources and/or resources that don't fill the canvas.

**Comment by sammeltassen** [comment]
I've been thinking: why was control of canvas aspect ratio important in the first place? You could indeed arrange and scale annotations on the canvas freely and determine canvas dimensions based on their shared outline and the smallest/largest annotation.

The reason why we needed control over aspect ratio had to do with the difference between preview and zoom modal in our digital exhibitions. The size of the preview blocks is determined by behaviour properties (eg. w-4, h-6). In order to fit the canvas content correctly in the block, it needed to have the same proportions.

Here're two screenshots of the problem. div.canvas-preview__center is larger than the preview block (it's a standard square canvas). In order for the preview to render correctly, I placed the objects on the top of the canvas. This explains why, when opening the modal, they're not in the center but at the top of the viewer (second image).

![Screenshot 2021-11-11 at 12 20 56](https://user-images.githubusercontent.com/747644/141290158-b4793719-4e02-427b-9178-39a96eb4a947.png)

![Screenshot 2021-11-11 at 12 21 03](https://user-images.githubusercontent.com/747644/141290232-7cb04baf-d1f2-4904-b960-afbee03dcbff.png)

(See exhibition made with the old manifest editor here: [https://heritage.tudelft.nl/en/exhibitions/rise-of-a-campus])

This issue could, I presume, also be solved within the exhibition component rather than the manifest editor. Because currently we're setting the dimensions twice, using behaviour properties and the canvas. (I remember that initially the plan was to generate thumbnails of mixed-media canvasses to avoid this problem, although then you'd still need to control the thumbnail's aspect ratio.)

Also take into account that you'd usually want to add some outer margin to mixed-media canvasses (although this could also be added later in the viewer application).

I have not rethought the exhibition component and would be open to reconsider our approach to preview/modal...

**Comment by sammeltassen** [comment]
(https://github.com/digirati-co-uk/iiif-manifest-editor/issues/17#issuecomment-963300881) Agreed about regions solving need for negative coordinates indeed.

**Comment by tomcrane** [comment]
Task - design the canvas UI

This feels like:

Most users never consider the canvas dimensions at all. They just think in terms of content because there's only one piece of content. The manifest editor just works for them and they don't set Canvas dimensions. It's just a sequence of images - or AV.

The editing surface doesn't even suggest a canvas. It's just an image.

Adding more than one `painting` resource to the canvas changes the behaviour slightly. The canvas will still default to the bounding rectangle, but you can see that there is a canvas, as long as there's a disjoint (content 2 not wholly enclosed by content 1)

There's a button that makes the canvas borders editable so you can move them. You can activate this, and they stay at the dimensions they were when you pressed the button, unless you drag them.

When this is activated you can also enter width and height manually and see the effects.

(mockups to follow)

**Comment by tomcrane** [comment]
I started a discussion for this at https://github.com/digirati-co-uk/iiif-manifest-editor/discussions/29

**Comment by tomcrane** [comment]
We should close discussion on this and agree what we're going to do across:

 - [ ] what's solved in the exhibition code rather than in providing settings in the Manifest
 - [ ] Aspect ratio settings #206 
 - [ ] Cropping #31

**Comment by stephenwf** [comment]
This has been improved, although having "fixed" size or aspect ratio canvases is not something we support. With the other tickets opened, closing this one for now.
