### ISSUE TITLE
Edit the label of a Manifest

### ISSUE THREAD

**Issue by tomcrane** [digirati-co-uk/iiif-manifest-editor#59]
Given a loaded Manifest (e.g., via #58), the user can make a change to it and save the results.

The UI is not so important here, just putting the pieces together.
This is, however, the beginning of the language map widget and we can take a look and see how we want to do that once this is done - the value editor here will be reusable in multiple places.

## Acceptance

- [x] When a Manifest is loaded, there is some means of selecting that I want to edit the label
- [x] When that selection is made, there is some contextual display on the right hand side that lets me edit the Manifest label
- [ ] This is not just a text box. 
    - [x] I can specify the language of the string
    - [x] I can have more than one string
    - [x] I can have more than one language
    - [x] The languages are constrained to a list of [two-letter language codes](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes), plus the special string `none`.
    - [ ] I can put the entries in order
- [x] When saved by some other mechanism, the label appears correctly in the serialised manifest. 

## Notes

We need to experiment with ways of presenting this simply - language maps can look weird if you are just expecting to edit a string.

**Comment by diegolago** [comment]
See latest wireframes for this. It summarises what we discussed yesterday and adds a bit of direction:

- Move and delete buttons are hidden by default. They should when the input field is on focus (need to test for accessibility)
- Move is on the left and delete on the right of the input field - doubled checked this with other products
- Delete icon is a bin rather than a cross which is already use to represent closing.
- Language selector is on the left hand side and it's part of the input field - these look connected.
